version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-document-ms-factorial-dev
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --logpath=/dev/null
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 5s
      timeout: 1s
      retries: 10

  app:
    tty: true # Enables debugging capabilities when attached to this container.
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: document-ms-factorial-api
    command: >
      sh -c "
        if [ -f tmp/pids/server.pid ]; then
          rm tmp/pids/server.pid
        fi
        bundle exec puma"
    depends_on:
      mongodb:
        condition: service_healthy

    ports:
      - 3000:3000
    volumes:
      - .:/document_ms
    environment:
      MONGODB_URI: mongodb://mongo-document-ms-factorial-dev:27017/mongo-document-ms-factorial-dev

