version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-document-ms-factorial-test
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --logpath=/dev/null
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 5s
      timeout: 1s
      retries: 10

  test:
    tty: true # Enables debugging capabilities when attached to this container.
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: document-ms-factorial-test
    command: >
      sh -c "
        bundle exec rubocop &&
        bundle exec rspec"
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/document_ms
    environment:
      MONGODB_URI_TEST: mongodb://mongo-document-ms-factorial-test:27017/mongo-document-ms-factorial-test
