development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      read:
        mode: :primary_preferred
      options:
        max_pool_size: 25
        min_pool_size: 1
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI_TEST'] %>
      options:
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_pool_size: 25
        min_pool_size: 1
  options:
    raise_not_found_error: false

staging:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      read:
        mode: :primary_preferred
      options:
        max_pool_size: 25
        min_pool_size: 1
  options:
    raise_not_found_error: false

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      read:
        mode: :primary_preferred
      options:
        max_pool_size: 25
        min_pool_size: 1
  options:
    raise_not_found_error: false
